### ISSUE TITLE
0.1.8 breaks Twilio support - Twilio is not a class (TypeError)

### ISSUE THREAD

**Issue by rosskevin** [mhs/sms-spec#13]
``` ruby
/home/apps/.rvm/gems/ruby-1.9.3-p448@acme/gems/sms-spec-0.1.8/lib/sms_spec/drivers/twilio-ruby.rb:1:in `<top (required)>': Twilio is not a class (TypeError)
from /home/apps/.rvm/gems/ruby-1.9.3-p448@acme/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:229:in `require'
from /home/apps/.rvm/gems/ruby-1.9.3-p448@acme/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:229:in `block in require'
from /home/apps/.rvm/gems/ruby-1.9.3-p448@acme/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:214:in `load_dependency'
from /home/apps/.rvm/gems/ruby-1.9.3-p448@acme/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:229:in `require'
from /home/apps/.rvm/gems/ruby-1.9.3-p448@acme/gems/sms-spec-0.1.8/lib/sms_spec.rb:13:in `driver='
```

I see that this gem version 0.1.8 was deployed by @manleycode from https://github.com/manlycode/sms-spec, but that repo has no issue tracking as it is a fork.

**Comment by manlycode** [comment]
I'm the maintainer of this. I've enabled Issue tracking on the current repo.

https://github.com/manlycode/sms-spec

**Comment by rosskevin** [comment]
Closing, moved to fork https://github.com/manlycode/sms-spec/issues/1
